### ISSUE TITLE
ei.associateEntity(agentName, entityName); not throwing RelationException on connection refused

### ISSUE THREAD

**Issue by Boblogic07** [agentcontest/massim#4]
IF a Server is not present at ei.associateEntity is called, no exception is thrown to inform the user that the connection has failed.

**Comment by t-ah** [comment]
Before connecting, the association/relation manipulation has already succeeded. 
I have added a method for checking an entity's connection status to the env. interface for now: 069df97a5b1efca5ac61080a8c30a1005c261169

I believe most implementations by now assume it is sufficient to call associateEntity(e, a) only once in the beginning since there are numerous later calls to entity.establishConnection() as well.

**Comment by Boblogic07** [comment]
Thank you!
